Fix postgres_status before first connection attempt It's possible to call postgres_status before the first connection is established. Before this fix, an exception was raised due to `self._postgres_connected` being `None`.
```
  File "/home/ar/code/github/sprockets/sprockets-postgres/sprockets_postgres.py", line 411, in postgres_status
    if not self._postgres_connected.is_set():
AttributeError: 'NoneType' object has no attribute 'is_set'
```